services:
  couchbase:
    image: couchbase:community-7.6.2
    env_file:
      - .env
    ports:
      - "8091-8097:8091-8097"
      - "9123:9123"
      - "11207:11207"
      - "11210:11210"
      - "11280:11280"
      - "18091-18097:18091-18097"
    volumes:
      - couchbase_data:/opt/couchbase/var
    restart: unless-stopped

volumes:
  couchbase_data:
