package com.miti99.storescraperbot.api.old.apple.response;

import java.util.List;
import java.util.Map;

public record AppleAppResponse(
    long id,
    String appId,
    String title,
    String url,
    String description,
    String icon,
    List<String> genres,
    List<String> genreIds,
    String primaryGenre,
    int primaryGenreId,
    String contentRating,
    List<String> languages,
    String size,
    String requiredOsVersion,
    String released,
    String updated,
    String releaseNotes,
    String version,
    double price,
    String currency,
    boolean free,
    long developerId,
    String developer,
    String developerUrl,
    String developerWebsite,
    double score,
    int reviews,
    double currentVersionScore,
    int currentVersionReviews,
    List<String> screenshots,
    List<String> ipadScreenshots,
    List<String> appletvScreenshots,
    List<String> supportedDevices,
    long ratings,
    Map<String, Long> histogram) {}
